import Head from 'next/head'
import { Rubik } from '@next/font/google'
import { AuthProvider } from '@/context/AuthContext'
import Header from '@/components/header/Header'
import '../scss/main.scss'

const rubik = Rubik({ subsets: ['latin'] })

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AuthProvider>
        <main className={rubik.className}>
          <Header />
          <section>
            <Component {...pageProps} />
          </section>
        </main>
      </AuthProvider>
    </>
  )
}
